//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перевозчик.
    /// </summary>
    // *** Start programmer edit section *** (Перевозчик1 CustomAttributes)

    // *** End programmer edit section *** (Перевозчик1 CustomAttributes)
    [AutoAltered()]
    [Caption("Перевозчик")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПеревозчикE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ПеревозчикL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Перевозчик1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Перевозчик1 CustomMembers)

        // *** End programmer edit section *** (Перевозчик1 CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Перевозчик1.Наименование CustomAttributes)

        // *** End programmer edit section *** (Перевозчик1.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Перевозчик1.Наименование Get start)

                // *** End programmer edit section *** (Перевозчик1.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Перевозчик1.Наименование Get end)

                // *** End programmer edit section *** (Перевозчик1.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перевозчик1.Наименование Set start)

                // *** End programmer edit section *** (Перевозчик1.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Перевозчик1.Наименование Set end)

                // *** End programmer edit section *** (Перевозчик1.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПеревозчикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеревозчикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеревозчикE", typeof(IIS.Kyrs9.Перевозчик1));
                }
            }
            
            /// <summary>
            /// "ПеревозчикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеревозчикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеревозчикL", typeof(IIS.Kyrs9.Перевозчик1));
                }
            }
        }
    }
}
