//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покуп или возв Б.
    /// </summary>
    // *** Start programmer edit section *** (ПокупИлиВозвБ CustomAttributes)

    // *** End programmer edit section *** (ПокупИлиВозвБ CustomAttributes)
    [AutoAltered()]
    [Caption("Покуп или возв Б")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупИлиВозвБE", new string[] {
            "Дата as \'Дата\'",
            "ПунктОтправ as \'Пункт отправления\'",
            "ПунктНазнач as \'Пункт назначения\'",
            "Перевозчик1",
            "Перевозчик1.Наименование as \'Перевозчик\'",
            "БилетнаяКасса as \'Место расчета\'",
            "БилетнаяКасса.Наименование as \'Место расчета\'",
            "БилетнаяКасса.Адрес as \'Адрес расчета\'",
            "Статус as \'Статус\'"})]
    [AssociatedDetailViewAttribute("ПокупИлиВозвБE", "ПокупкаБилета", "ПокупкаБилетаE", false, "", "Покупка билета", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПокупИлиВозвБE", "ВозвратБилета", "ВозвратБилетаE", false, "", "Возврат билета", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПокупИлиВозвБE", "Перевозчик1", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Перевозчик")]
    [MasterViewDefineAttribute("ПокупИлиВозвБE", "БилетнаяКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Место расчета")]
    [View("ПокупИлиВозвБL", new string[] {
            "Дата as \'Дата\'",
            "ПунктОтправ as \'Пункт отправления\'",
            "ПунктНазнач as \'Пункт назначения\'",
            "Перевозчик1.Наименование as \'Перевозчик\'",
            "БилетнаяКасса.Наименование as \'Место расчета\'",
            "БилетнаяКасса.Адрес as \'Адрес расчета\'",
            "Статус as \'Статус\'"})]
    [AssociatedDetailViewAttribute("ПокупИлиВозвБL", "ПокупкаБилета", "ПокупкаБилетаE", false, "", "Покупка билета", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПокупИлиВозвБL", "ВозвратБилета", "ВозвратБилетаE", false, "", "Возврат билета", true, new string[] {
            ""})]
    public class ПокупИлиВозвБ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fПунктОтправ;
        
        private string fПунктНазнач;
        
        private IIS.Kyrs9.Статус fСтатус;
        
        private IIS.Kyrs9.Перевозчик1 fПеревозчик1;
        
        private IIS.Kyrs9.БилетнаяКасса fБилетнаяКасса;
        
        private IIS.Kyrs9.DetailArrayOfВозвратБилета fВозвратБилета;
        
        private IIS.Kyrs9.DetailArrayOfПокупкаБилета fПокупкаБилета;
        
        // *** Start programmer edit section *** (ПокупИлиВозвБ CustomMembers)

        // *** End programmer edit section *** (ПокупИлиВозвБ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.Дата CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Дата Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Дата Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Дата Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Дата Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПунктНазнач.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктНазнач
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Get start)
                string result = this.fПунктНазнач;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Set start)
                this.fПунктНазнач = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктНазнач Set end)
            }
        }
        
        /// <summary>
        /// ПунктОтправ.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктОтправ
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Get start)
                string result = this.fПунктОтправ;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Set start)
                this.fПунктОтправ = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПунктОтправ Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.Статус CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.Статус CustomAttributes)
        public virtual IIS.Kyrs9.Статус Статус
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Статус Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Статус Get start)
                IIS.Kyrs9.Статус result = this.fСтатус;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Статус Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Статус Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Статус Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Покуп или возв Б.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса CustomAttributes)
        [PropertyStorage(new string[] {
                "БилетнаяКасса"})]
        [NotNull()]
        public virtual IIS.Kyrs9.БилетнаяКасса БилетнаяКасса
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Get start)
                IIS.Kyrs9.БилетнаяКасса result = this.fБилетнаяКасса;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Set start)
                this.fБилетнаяКасса = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.БилетнаяКасса Set end)
            }
        }
        
        /// <summary>
        /// Покуп или возв Б.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 CustomAttributes)
        [PropertyStorage(new string[] {
                "Перевозчик1"})]
        [NotNull()]
        public virtual IIS.Kyrs9.Перевозчик1 Перевозчик1
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Get start)
                IIS.Kyrs9.Перевозчик1 result = this.fПеревозчик1;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Set start)
                this.fПеревозчик1 = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.Перевозчик1 Set end)
            }
        }
        
        /// <summary>
        /// Покуп или возв Б.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета CustomAttributes)
        public virtual IIS.Kyrs9.DetailArrayOfВозвратБилета ВозвратБилета
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Get start)
                if ((this.fВозвратБилета == null))
                {
                    this.fВозвратБилета = new IIS.Kyrs9.DetailArrayOfВозвратБилета(this);
                }
                IIS.Kyrs9.DetailArrayOfВозвратБилета result = this.fВозвратБилета;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Set start)
                this.fВозвратБилета = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ВозвратБилета Set end)
            }
        }
        
        /// <summary>
        /// Покуп или возв Б.
        /// </summary>
        // *** Start programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета CustomAttributes)

        // *** End programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета CustomAttributes)
        public virtual IIS.Kyrs9.DetailArrayOfПокупкаБилета ПокупкаБилета
        {
            get
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Get start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Get start)
                if ((this.fПокупкаБилета == null))
                {
                    this.fПокупкаБилета = new IIS.Kyrs9.DetailArrayOfПокупкаБилета(this);
                }
                IIS.Kyrs9.DetailArrayOfПокупкаБилета result = this.fПокупкаБилета;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Get end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Set start)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Set start)
                this.fПокупкаБилета = value;
                // *** Start programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Set end)

                // *** End programmer edit section *** (ПокупИлиВозвБ.ПокупкаБилета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупИлиВозвБE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупИлиВозвБE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупИлиВозвБE", typeof(IIS.Kyrs9.ПокупИлиВозвБ));
                }
            }
            
            /// <summary>
            /// "ПокупИлиВозвБL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупИлиВозвБL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупИлиВозвБL", typeof(IIS.Kyrs9.ПокупИлиВозвБ));
                }
            }
        }
    }
}
