//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покупатель.
    /// </summary>
    // *** Start programmer edit section *** (Покупатель CustomAttributes)

    // *** End programmer edit section *** (Покупатель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупательE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "БанковскийСчет as \'Банковский счет\'"})]
    [View("ПокупательL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "БанковскийСчет as \'Банковский счет\'"})]
    public class Покупатель : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private string fБанковскийСчет;
        
        // *** Start programmer edit section *** (Покупатель CustomMembers)

        // *** End programmer edit section *** (Покупатель CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ID CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ID Get start)

                // *** End programmer edit section *** (Покупатель.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Покупатель.ID Get end)

                // *** End programmer edit section *** (Покупатель.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ID Set start)

                // *** End programmer edit section *** (Покупатель.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Покупатель.ID Set end)

                // *** End programmer edit section *** (Покупатель.ID Set end)
            }
        }
        
        /// <summary>
        /// БанковскийСчет.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.БанковскийСчет CustomAttributes)

        // *** End programmer edit section *** (Покупатель.БанковскийСчет CustomAttributes)
        [StrLen(255)]
        public virtual string БанковскийСчет
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.БанковскийСчет Get start)

                // *** End programmer edit section *** (Покупатель.БанковскийСчет Get start)
                string result = this.fБанковскийСчет;
                // *** Start programmer edit section *** (Покупатель.БанковскийСчет Get end)

                // *** End programmer edit section *** (Покупатель.БанковскийСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.БанковскийСчет Set start)

                // *** End programmer edit section *** (Покупатель.БанковскийСчет Set start)
                this.fБанковскийСчет = value;
                // *** Start programmer edit section *** (Покупатель.БанковскийСчет Set end)

                // *** End programmer edit section *** (Покупатель.БанковскийСчет Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ФИО Get start)

                // *** End programmer edit section *** (Покупатель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Покупатель.ФИО Get end)

                // *** End programmer edit section *** (Покупатель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ФИО Set start)

                // *** End programmer edit section *** (Покупатель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Покупатель.ФИО Set end)

                // *** End programmer edit section *** (Покупатель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательE", typeof(IIS.Kyrs9.Покупатель));
                }
            }
            
            /// <summary>
            /// "ПокупательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательL", typeof(IIS.Kyrs9.Покупатель));
                }
            }
        }
    }
}
