//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Оплачено CustomAttributes)

        // *** End programmer edit section *** (Статус.Оплачено CustomAttributes)
        [Caption("Оплачено")]
        Оплачено,
        
        // *** Start programmer edit section *** (Статус.НеОплачено CustomAttributes)

        // *** End programmer edit section *** (Статус.НеОплачено CustomAttributes)
        [Caption("Не оплачено")]
        НеОплачено,
        
        // *** Start programmer edit section *** (Статус.Возврат CustomAttributes)

        // *** End programmer edit section *** (Статус.Возврат CustomAttributes)
        [Caption("Возврат")]
        Возврат,
    }
}
